// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Roles struct {
	ID                int32
	Name              string
	Alignment         sql.NullString
	Description       sql.NullString
	PerksJson         pqtype.NullRawMessage
	StartingItemsJson pqtype.NullRawMessage
	CreatedAt         sql.NullTime
}

type Sessions struct {
	ID         uuid.UUID
	PlayerName string
	CreatedAt  sql.NullTime
	LastSeen   sql.NullTime
}
