// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Actions struct {
	ID        uuid.UUID
	PlayerID  uuid.NullUUID
	Type      string
	TargetID  uuid.NullUUID
	RoomCode  string
	Phase     string
	Timestamp sql.NullTime
}

type Players struct {
	ID       uuid.UUID
	Name     string
	RoomCode string
	RoleID   sql.NullInt32
	IsAlive  sql.NullBool
	JoinedAt sql.NullTime
}

type Roles struct {
	ID                int32
	Name              string
	Alignment         sql.NullString
	Description       sql.NullString
	PerksJson         pqtype.NullRawMessage
	StartingItemsJson pqtype.NullRawMessage
	CreatedAt         sql.NullTime
}

type Rooms struct {
	Code      string
	HostID    uuid.UUID
	Phase     string
	CreatedAt sql.NullTime
}

type Sessions struct {
	ID         uuid.UUID
	PlayerName string
	CreatedAt  sql.NullTime
	LastSeen   sql.NullTime
}
