// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Actions struct {
	ID         pgtype.UUID
	RoomID     pgtype.UUID
	PlayerID   pgtype.UUID
	ActionType string
	TargetID   pgtype.UUID
	Phase      string
	CreatedAt  pgtype.Timestamptz
}

type Players struct {
	ID       pgtype.UUID
	RoomID   pgtype.UUID
	Name     string
	RoleID   pgtype.Int4
	IsAlive  pgtype.Bool
	JoinedAt pgtype.Timestamptz
}

type Roles struct {
	ID          int32
	Name        string
	Description pgtype.Text
	Team        string
	CreatedAt   pgtype.Timestamptz
}

type Rooms struct {
	ID        pgtype.UUID
	Code      string
	HostID    string
	Phase     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
