// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, name, alignment, description, perks_json, starting_items_json
FROM roles
WHERE id = $1
`

type GetRoleByIDRow struct {
	ID                int32
	Name              string
	Alignment         sql.NullString
	Description       sql.NullString
	PerksJson         pqtype.NullRawMessage
	StartingItemsJson pqtype.NullRawMessage
}

func (q *Queries) GetRoleByID(ctx context.Context, id int32) (GetRoleByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getRoleByID, id)
	var i GetRoleByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Alignment,
		&i.Description,
		&i.PerksJson,
		&i.StartingItemsJson,
	)
	return i, err
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, alignment, description, perks_json, starting_items_json
FROM roles
ORDER BY name
`

type ListRolesRow struct {
	ID                int32
	Name              string
	Alignment         sql.NullString
	Description       sql.NullString
	PerksJson         pqtype.NullRawMessage
	StartingItemsJson pqtype.NullRawMessage
}

func (q *Queries) ListRoles(ctx context.Context) ([]ListRolesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRolesRow
	for rows.Next() {
		var i ListRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Alignment,
			&i.Description,
			&i.PerksJson,
			&i.StartingItemsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
