CREATE TABLE roles (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    alignment VARCHAR(50),
    description TEXT,
    perks_json JSONB,
    starting_items_json JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sessions (
    id UUID PRIMARY KEY,
    player_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE rooms (
    code VARCHAR(10) PRIMARY KEY,
    host_id UUID NOT NULL,
    phase VARCHAR(20) NOT NULL DEFAULT 'LOBBY',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE players (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    room_code VARCHAR(10) NOT NULL REFERENCES rooms(code) ON DELETE CASCADE,
    role_id INT REFERENCES roles(id),
    is_alive BOOLEAN DEFAULT TRUE,
    joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE actions (
    id UUID PRIMARY KEY,
    player_id UUID REFERENCES players(id) ON DELETE CASCADE,
    type VARCHAR(50) NOT NULL,
    target_id UUID,
    room_code VARCHAR(10) NOT NULL REFERENCES rooms(code) ON DELETE CASCADE,
    phase VARCHAR(20) NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

